###
GET http://localhost:3000/api/jokes

###

GET http://localhost:3000/jokes/random

###

GET http://localhost:3000/jokes/1

###

POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "question": "Quel est le sport le plus silencieux ?",
    "response": "Le para-chuuuuute."
}

