###
GET http://localhost:3000/api/jokes

###

GET http://localhost:3000/api/jokes/random

###

GET http://localhost:3000/api/jokes/1

###

POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "question": "Quelle est la femelle du hamster ?",
    "response": "L’Amsterdam"
}

